### ISSUE TITLE
EC2 instances without IAM roles can't start Propsd

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/propsd#216]
If an EC2 instances doesn't have an IAM role, it won't get security credentials. The code that [parses EC2 metadata](https://github.com/rapid7/propsd/blob/v1.4.3/lib/source/metadata/util.js) will fail to parse the [/meta-data/iam/security-credentials/ path](https://github.com/rapid7/propsd/blob/v1.4.3/lib/source/metadata/parser.js#L89-L103). The error returned to the user looks something like this:
```
{"level":"ERROR","message":"Aws-sdk returned the following error during the metadata service request to /latest/meta-data/iam/security-credentials/: {\"message\":null,\"retryable\":false,\"time\":\"1970-01-01T00:00:00.000Z\"}","timestamp":"1970-01-01T00:00:00.000Z"}
    /opt/propsd-1.4.4/lib/source/metadata/util.js:87
            const items = data.trim().split('\n');
 TypeError: data.trim is not a function
        at /opt/propsd-1.4.4/lib/source/metadata/util.js:87:28
        at /opt/propsd-1.4.4/lib/source/metadata.js:78:18
        at errCallback (/opt/propsd-1.4.4/node_modules/aws-sdk/lib/util.js:833:9)
        at IncomingMessage.<anonymous> (/opt/propsd-1.4.4/node_modules/aws-sdk/lib/util.js:851:13)
        at emitNone (events.js:72:20)
        at IncomingMessage.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:923:12)
        at nextTickCallbackWith2Args (node.js:458:9)
        at process._tickDomainCallback (node.js:413:17)
```

**Comment by dgreene-r7** [comment]
This is a duplicate of #232.
