### ISSUE TITLE
Propsd fails if it can't reach the EC2 metadata service

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/propsd#232]
If I run Propsd in Vagrant, where I don't have an EC2 metadata service, I see this error in the logs.
```
{"level":"ERROR","message":"Aws-sdk returned the following error during the metadata service request to /latest/meta-data/iam/security-credentials/: {\"code\":\"ENETUNREACH\",\"errno\":\"ENETUNREACH\",\"syscall\":\"connect\",\"address\":\"169.254.169.254\",\"port\":80}","timestamp":"2017-03-29T14:19:14.567Z"}
/opt/propsd-1.5.0/lib/source/metadata/util.js:87
        const items = data.trim().split('\n');
                           ^

TypeError: data.trim is not a function
    at /opt/propsd-1.5.0/lib/source/metadata/util.js:87:28
    at ClientRequest.<anonymous> (/opt/propsd-1.5.0/lib/source/metadata.js:78:18)
    at ClientRequest.<anonymous> (/opt/propsd-1.5.0/node_modules/aws-sdk/lib/http/node.js:62:19)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1272:8)
    at nextTickCallbackWith2Args (node.js:511:9)
```

Propsd should work even if an EC2 metadata service isn't available.

**Comment by dgreene-r7** [comment]
I'm glad you filed this ticket. I was poking today at the `source/metadata/*` stuff and it's dire need of a refactor. The [`Metadata#_fetch`](https://github.com/rapid7/propsd/blob/master/lib/source/metadata.js#L65-L110) function is particularly agregious and could be fixed up pretty easily.

I propose we create a `Refactor` project and file a couple of tickets under it.
